export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
//
export const FAVORITES_LOADING = 'FAVORITES_LOADING'
export const FAVORITES_FAILED = 'FAVORITES_FAILED'
export const ADD_FAVORITES = 'ADD_FAVORITES'
//
export const SHOW_LOG_FORM = 'SHOW_LOG_FORM'
export const HIDE_LOG_FORM = 'HIDE_LOG_FORM'
export const CHANGE_FORM = 'CHANGE_FORM'
